In [1]:
import numpy as np

In [5]:
!conda activate test

Did not find path entry C:\Users\ad\miniconda3\bin


In [7]:
a = 1
b = 1
id(a) == id(b)

True

In [16]:
a = np.array([[8,12],[7,1]])
a

array([[ 8, 12],
       [ 7,  1]])

In [17]:
np.sort(a)

array([[ 8, 12],
       [ 1,  7]])

In [18]:
a

array([[ 8, 12],
       [ 7,  1]])

In [19]:
np.sort(a, axis= 0)

array([[ 7,  1],
       [ 8, 12]])

In [20]:
a

array([[ 8, 12],
       [ 7,  1]])

In [21]:
np.sort(a)

array([[ 8, 12],
       [ 1,  7]])

In [23]:
import sklearn
sklearn.__version__

'0.24.2'

In [24]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [28]:
iris = load_iris()
type(iris)
#iris

sklearn.utils.Bunch

In [29]:
# 딕셔너리 형태이기 때문에 키로 추출가능
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [32]:
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [41]:
import pandas as pd
iris_data  = iris['data']
iris_label = iris['target_names']
iris_df = pd.DataFrame(data=iris_data, columns =iris['feature_names'])
iris_df
iris_df['label'] = iris['target']
iris_df.sample()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
139                6.9               3.1                5.4               2.1   

     label  
139      2

In [45]:
train_test_split(iris_data, iris['target'], test_size=0.2, random_state=11 )

[array([[5.1, 3.5, 1.4, 0.2],
        [6.9, 3.2, 5.7, 2.3],
        [7.7, 2.8, 6.7, 2. ],
        [5. , 3.3, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [7.7, 2.6, 6.9, 2.3],
        [7.6, 3. , 6.6, 2.1],
        [6.7, 3. , 5. , 1.7],
        [5.5, 3.5, 1.3, 0.2],
        [6. , 2.7, 5.1, 1.6],
        [5. , 2. , 3.5, 1. ],
        [7.9, 3.8, 6.4, 2. ],
        [4.6, 3.4, 1.4, 0.3],
        [6.9, 3.1, 4.9, 1.5],
        [6.5, 3. , 5.8, 2.2],
        [5.1, 2.5, 3. , 1.1],
        [6.6, 2.9, 4.6, 1.3],
        [5. , 3.2, 1.2, 0.2],
        [7.4, 2.8, 6.1, 1.9],
        [5.1, 3.8, 1.6, 0.2],
        [6.8, 3.2, 5.9, 2.3],
        [6.9, 3.1, 5.1, 2.3],
        [5.9, 3. , 4.2, 1.5],
        [4.9, 2.5, 4.5, 1.7],
        [6.7, 3.1, 4.7, 1.5],
        [4.4, 3.2, 1.3, 0.2],
        [5.4, 3.4, 1.7, 0.2],
        [6.5, 2.8, 4.6, 1.5],
        [5.1, 3.7, 1.5, 0.4],
        [5. , 3.4, 1.6, 0.4],
        [6.1, 2.6, 5.6, 1.4],
        [6.5, 3. , 5.5, 1.8],
        [6.3, 2.5, 5. , 1.9],
        [5

In [54]:
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris['target'], test_size=0.2, random_state=11 )

In [53]:
train_test_split(arrays=iris_data, test_size=0.2, random_state=11 )
# 가변 인수는 지정불가? arrays= 없이써야함

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (<ipython-input-53-89f0ec11b1aa>, line 1)

In [55]:
dt_clf = DecisionTreeClassifier(random_state=11)

In [57]:
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=11)

In [68]:
pred = dt_clf.predict(x_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [61]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [79]:
from sklearn.metrics import accuracy_score
print(f'예측정확도 {round(accuracy_score(y_test,pred),4)}')
print('예측정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

예측정확도 0.9333
예측정확도:0.9333


In [86]:
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [90]:
dt_clf.predict([[5.1,3.2,1.7,0.5]])
# 위의 4개를 넣으면
# 레이블을 0번으로 예측

array([0])

In [92]:
a= sklearn.preprocessing

In [93]:
a.add_dummy_feature()

TypeError: add_dummy_feature() missing 1 required positional argument: 'X'

In [95]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris['data']
label    = iris['target']
dt_clf = DecisionTreeClassifier(random_state=156)

In [100]:
kfold = KFold(n_splits=5)
cv_accuracy = list()
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [108]:
list(kfold.split(features))

[(array([ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
          43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
          69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
          82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
          95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
         108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
         121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
         134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
         147, 148, 149]),
  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])),
 (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27, 

In [107]:
for train_index, test_index in kfold.split(iris['data']):
    print(train_index)
    print(test_index)
    break

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [124]:
n_iter = 0

for train_index, test_index in kfold.split(iris['data']):
    X_train, X_test = iris.data[train_index],iris.data[test_index]
    y_train, y_test = iris['target'][train_index],iris['target'][test_index]

    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n# {0} 교차 정확도:{1}, 학습데이터 크기: {2}, 검증데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
    print('{0} 검증 세트 인덱스{1}'. format(n_iter, test_index))
    cv_accuracy.append(accuracy)

    print('\n ## 평균 검증 정확도:', np.mean(cv_accuracy))


# 1 교차 정확도:1.0, 학습데이터 크기: 120, 검증데이터 크기 : 30
1 검증 세트 인덱스[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 ## 평균 검증 정확도: 0.9285714285714286

# 2 교차 정확도:0.9667, 학습데이터 크기: 120, 검증데이터 크기 : 30
2 검증 세트 인덱스[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

 ## 평균 검증 정확도: 0.9333374999999999

# 3 교차 정확도:0.8667, 학습데이터 크기: 120, 검증데이터 크기 : 30
3 검증 세트 인덱스[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

 ## 평균 검증 정확도: 0.9259333333333333

# 4 교차 정확도:0.9333, 학습데이터 크기: 120, 검증데이터 크기 : 30
4 검증 세트 인덱스[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

 ## 평균 검증 정확도: 0.92667

# 5 교차 정확도:0.7333, 학습데이터 크기: 120, 검증데이터 크기 : 30
5 검증 세트 인덱스[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 ## 평균 검증 정확도: 0.9090909090909091


In [118]:
(iris['data'])[0]

array([5.1, 3.5, 1.4, 0.2])

In [125]:
import pandas as pd
iris =load_iris()
iris_df = pd.DataFrame(iris['data'], columns=iris['feature_names'] )
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [127]:
iris_df['label'] = iris['target']
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [128]:
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [129]:
kfold = KFold(n_splits=3) # 데이터 종류가 2개이기 때문
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test  = iris_df['label'].iloc[test_index]
    print(f'## 교차검증:{n_iter}')
    print(f'학습레이블 데이터분포:\n{label_train.value_counts()}')
    print(f'검증레이블 데이터분포:\n{label_test.value_counts()}')

## 교차검증:1
학습레이블 데이터분포:
1    50
2    50
Name: label, dtype: int64
검증레이블 데이터분포:
0    50
Name: label, dtype: int64
## 교차검증:2
학습레이블 데이터분포:
0    50
2    50
Name: label, dtype: int64
검증레이블 데이터분포:
1    50
Name: label, dtype: int64
## 교차검증:3
학습레이블 데이터분포:
0    50
1    50
Name: label, dtype: int64
검증레이블 데이터분포:
2    50
Name: label, dtype: int64


In [130]:
kfold = KFold(n_splits=3,shuffle=True) # 데이터 종류가 2개이기 때문
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test  = iris_df['label'].iloc[test_index]
    print(f'## 교차검증:{n_iter}')
    print(f'학습레이블 데이터분포:\n{label_train.value_counts()}')
    print(f'검증레이블 데이터분포:\n{label_test.value_counts()}')

## 교차검증:1
학습레이블 데이터분포:
0    42
1    30
2    28
Name: label, dtype: int64
검증레이블 데이터분포:
2    22
1    20
0     8
Name: label, dtype: int64
## 교차검증:2
학습레이블 데이터분포:
2    39
1    35
0    26
Name: label, dtype: int64
검증레이블 데이터분포:
0    24
1    15
2    11
Name: label, dtype: int64
## 교차검증:3
학습레이블 데이터분포:
1    35
2    33
0    32
Name: label, dtype: int64
검증레이블 데이터분포:
0    18
2    17
1    15
Name: label, dtype: int64


In [136]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3) # 데이터 종류가 2개이기 때문
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df.label):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test  = iris_df['label'].iloc[test_index]
    print(f'## 교차검증:{n_iter}')
    print(f'학습레이블 데이터분포:\n{label_train.value_counts()}')
    print(f'검증레이블 데이터분포:\n{label_test.value_counts()}')

## 교차검증:1
학습레이블 데이터분포:
2    34
0    33
1    33
Name: label, dtype: int64
검증레이블 데이터분포:
0    17
1    17
2    16
Name: label, dtype: int64
## 교차검증:2
학습레이블 데이터분포:
1    34
0    33
2    33
Name: label, dtype: int64
검증레이블 데이터분포:
0    17
2    17
1    16
Name: label, dtype: int64
## 교차검증:3
학습레이블 데이터분포:
0    34
1    33
2    33
Name: label, dtype: int64
검증레이블 데이터분포:
1    17
2    17
0    16
Name: label, dtype: int64


In [137]:
dt_clf = DecisionTreeClassifier(random_state=156)
skfold = StratifiedKFold(n_splits=3) # 데이터 종류가 2개이기 때문
n_iter = 0
cv_accuracy = list()

for train_index, test_index in skfold.split(iris_df, iris_df.label):

    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    print(f'\n#{n_iter} 교차 검증 정확도 : {accuracy}, 학습 데이터 크기 : {train_size}, 검증데이터 크기:{test_size}')
    print(f'#{n_iter} 검증 세트 인덱스: {test_index}')
    cv_accuracy.append(accuracy)


#1 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증데이터 크기:50
#1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.94, 학습 데이터 크기 : 100, 검증데이터 크기:50
#2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증데이터 크기:50
#3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


In [138]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf =DecisionTreeClassifier(random_state=156)

scores = cross_val_score(dt_clf, iris_data['data'], iris_data['target'], scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


In [141]:
scoring = ['accuracy', 'f1_micro']
scores1 = cross_validate(dt_clf, iris_data['data'], iris_data['target'], scoring=scoring, cv=3)
scores1


{'fit_time': array([0.0029943 , 0.00099707, 0.00099707]),
 'score_time': array([0.00598145, 0.00099659, 0.00199389]),
 'test_accuracy': array([0.98, 0.94, 0.98]),
 'test_f1_micro': array([0.98, 0.94, 0.98])}

In [146]:
from sklearn.model_selection import GridSearchCV

X_train, X_test, y_train, y_test = train_test_split(iris_data['data'], iris_data['target'], test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()
parameters = {'max_depth':[1,2,3],'min_samples_split':[2,3]} 


In [147]:
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

In [148]:
grid_dtree.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [150]:
scores_df =pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [151]:
from sklearn.preprocessing import LabelEncoder
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[0 1 4 5 3 3 2 2]


In [152]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [153]:
encoder.inverse_transform([0])

array(['TV'], dtype='<U5')

In [156]:
from sklearn.preprocessing import OneHotEncoder
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels.shape

(8,)

In [157]:
labels.reshape(-1, 1)


array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [155]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

ValueError: Expected 2D array, got 1D array instead:
array=[0 1 4 5 3 3 2 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [158]:
labels =labels.reshape(-1, 1)

In [159]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [160]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [161]:
oh_labels.shape

(8, 6)

In [163]:
oh_labels.toarray().tolist()

[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]]

In [164]:
df = pd.DataFrame(data = dict(item= ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']))
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [165]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [167]:
iris = load_iris()
iris_data = iris['data']
iris_df = pd.DataFrame(data = iris_data, columns = iris['feature_names'])
iris_df.sample(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
57                4.9               2.4                3.3               1.0
37                4.9               3.6                1.4               0.1

In [170]:
print(iris_df.mean())
print(f'분산\n{iris_df.var()}')

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
분산
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [172]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris_df)
iris_acaled = scaler.transform(iris_df)

In [173]:
iris_df_scaled = pd.DataFrame(data = iris_acaled, columns = iris['feature_names'])

In [174]:
print(iris_df_scaled.mean())
print(f'분산\n{iris_df_scaled.var()}')

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
분산
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [176]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns= iris['feature_names'])
iris_scaled
iris_df_scaled

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [177]:
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1,1)

In [180]:
scale = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
train_scaled

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [184]:
scaler  = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

test_scaled = scaler.transform(test_array)
test_scaled

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5]])

In [ ]:
# %tensorflow_version 1.7
import tensorflow as tf
tf.__version__

ModuleNotFoundError: No module named 'tensorflow'

In [6]:
import pandas as pd


SyntaxError: invalid syntax (Temp/ipykernel_12624/3063444854.py, line 2)

In [ ]:
import sys 
!{sys.executable} -m pip install tensorflow==1.15.0

ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.0
ERROR: No matching distribution found for tensorflow==1.15.0
